# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['Main.py'],
    pathex=['C:\\Users\\Nikita\\PycharmProjects\\PygameProject'],
    binaries=[],
    datas=[('data/arrow.png', '.'),
           ('data/balance panel.png', '.'),
           ('data/boost_cell1.png', '.'),
           ('data/boost_cell2.png', '.'),
           ('data/boost_cell3.png', '.'),
           ('data/cake.png', '.'),
           ('data/cell.png', '.'),
           ('data/cross_cell.png', '.'),
           ('data/fon.jpg', '.'),
           ('data/horizontal panel.png', '.'),
           ('data/icon.ico', '.'),
           ('data/locked_cell.png', '.'),
           ('data/lvl1_sprite.png', '.'),
           ('data/lvl2_sprite.png', '.'),
           ('data/lvl3_sprite.png', '.'),
           ('data/lvl4_sprite.png', '.'),
           ('data/lvl5_sprite.png', '.'),
           ('data/lvl6_sprite.png', '.'),
           ('data/lvl7_sprite.png', '.'),
           ('data/lvl8_sprite.png', '.'),
           ('data/lvl9_sprite.png', '.'),
           ('data/lvl10_sprite.png', '.'),
           ('data/music.mp3', '.'),
           ('data/price panel.png', '.'),
           ('data/results.txt', '.'),
           ('data/shop_cell1.png', '.'),
           ('data/shop_cell2.png', '.'),
           ('data/shop_cell3.png', '.'),
           ('data/shop_cell4.png', '.'),
           ('data/shop_cell5.png', '.'),
           ('data/shop_cell6.png', '.'),
           ('data/star.png', '.'),
           ('data/upgrade_button1.png', '.'),
           ('data/upgrade_button2.png', '.'),
           ('data/upgrade_button3.png', '.'),
           ('data/upgrade_button4.png', '.'),
           ('data/upgrade_button5.png', '.'),
           ('data/upgrade_button6.png', '.'),
           ('data/upgrade_button7.png', '.'),
           ('data/upgrade_button8.png', '.'),
           ('data/upgrade_button9.png', '.'),
           ('data/upgrade_button10.png', '.'),
           ('data/upgrade_button11.png', '.'),
           ('data/vertical panel.png', '.')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Merge Cakes',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['C:\\Users\\Nikita\\PycharmProjects\\PygameProject\\data\\icon.ico'],
)
